languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "小尛の博客"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/blowfish_logo_transparent.png"
  # description = "一个强大、轻量级的 Hugo 主题。"

[author]
  name = "XIAOMO"
  image = "img/blowfish_logo.png"
  headline = "我喜欢听花开的声音，更想自由地深情地呼吸"
  bio = "我喜欢听花开的声音，更想自由地深情地呼吸"
  # links = [
  #   { github = "https://github.com/nunocoracao/blowfish" },
  # ]

