[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "项目"
  pageRef = "docs"
  weight = 15

# [[main]]
#   name = "笔记"
#   weight = 20

# [[main]]
#   name = "A"
#   parent = "笔记"
#   pageRef = "categories"
#   weight = 16

# [[main]]
#   name = "B"
#   parent = "笔记"
#   pageRef = "content"
#   weight = 40

# [[main]]
#   name = "用户列表"
#   pageRef = "users"
#   weight = 90

# [[main]]
#   name = "周边"
#   url = "https://www.teepublic.com/user/blowfish-store/t-shirts"
#   weight = 100

# [[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

# [[main]]
#   identifier = "twitter"
#   pre = "x-twitter"
#   url = "https://twitter.com/burufugu"
#   weight = 200

# [[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

# [[main]]
#   identifier = "github"
#   pre = "github"
#   url = "https://github.com/nunocoracao/blowfish"
#   weight = 400


# -- Footer Menu --
[[footer]]
  # name = "关于作者"
  # pageRef = "authors"
  # weight = 20
